ethertoff/urls.py
from django.urls import path, re_path
from . import views

## FIXME: if uncommenting url namespacing will be needed
# app_name = "ethertoff"

urlpatterns = [
    path('', views.home, name='home'),
    path('all/', views.all, name='all'),
    path('manage/', views.manage, name='manage'),
    path('manage/<path:path>/', views.manage, name='manage'),
    path('publish/', views.publish, name='publish'),
    path('generate/', views.generate, name='generate'),
    path('css-screen/', views.css, name='css-screen'),
    path('css-print/', views.cssprint, name='css-print'),
    path('css-offset/', views.offsetprint, name='css-offset'),
    path('css-slide/', views.css_slide, name='css-slide'),
    path('create/', views.padCreate, name='pad-create'),
    path('create/<path:prefix>/', views.padCreate, name='pad-create'),
    path('rename-folder/', views.RenameFolderView.as_view(), name='folder-rename'),
    path('rename-folder/<path:prefix>/', views.RenameFolderView.as_view(), name='folder-rename'),
    path('rename/<int:pk>/', views.padRename, name='pad-rename'),
    path('delete/<int:pk>/', views.padDelete, name='pad-delete'),
    path('public/<int:pk>/', views.padPublic, name='pad-public'),
    path('private/<int:pk>/', views.padPrivate, name='pad-private'),
    re_path(r'(?P<mode>[r|s|p])/(?P<slug>[^/]+)$', views.pad_read, name='pad-read'),
    re_path(r'(?P<mode>[r|s|p])/(?P<slug>[^/]+)$', views.pad_read, name='pad'),
    re_path(r'(?P<mode>[w])/(?P<slug>[^/]+)$', views.pad, name='pad'),
    re_path(r'w/(?P<slug>[^/]+)$', views.pad, name='pad-write'),
    re_path(r'^(?P<slug>[^/]+)\.xhtml$', views.xhtml, name='xhtml'),
]

my_project/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# This is to allow the website to work under a subfolder
# i.e. http://ethertoff.be/2015/
# Define SUBFOLDER in your local_settings.py
BASE_URL = '^'
try:
    BASE_URL = r'^' + settings.SUBFOLDER
    if BASE_URL and not BASE_URL.endswith(r'/'):
        BASE_URL += r'/'
except AttributeError:
    pass

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("ethertoff.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns = [
    #path(BASE_URL , include(base_urlpatterns)),
#]

ethertoff/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    name         = forms.CharField(max_length=50, label=_("First Name"))
    email        = forms.EmailField(label=_("E-Mail"))
    subject      = forms.CharField(max_length=100, label=_("Subject"))
    message      = forms.CharField(widget=forms.Textarea(), label=_("Message"))

class RenameFolderForm(forms.Form):
    old_name = forms.CharField(label=_("Old name"), required=False)
    new_name = forms.CharField(label=_("New name"), required=False)

class PadRename(forms.Form):
    pk = forms.HiddenInput()
    name = forms.CharField(label=_("Name"))

ethertoff/views.py
# -*- coding: utf-8 -*-

# Python imports
import datetime
import time
import urllib
from urllib.parse import urlparse
from html.parser import HTMLParser
import json
import re
import os

# PyPi imports

import markdown
from markdown.extensions.toc import TocExtension
from mdx_semanticdata import SemanticDataExtension
from py_etherpad import EtherpadLiteClient
import dateutil.parser
import pytz

# Framework imports
from django.shortcuts import render, get_object_or_404, redirect

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.db import IntegrityError
from django.conf import settings
from django.contrib.staticfiles import finders

# Django Apps import

from etherpadlite.models import Pad, PadAuthor
from etherpadlite import forms
from etherpadlite import config

from ethertoff.management.commands.index import snif
from ethertoff.templatetags.wikify import wikifyPath, ensureTrailingSlash

from generator.management.commands.generate import generate as generateStatic

from . import forms as ethertoffForms

from ethertoff.forms import RenameFolderForm
from django.views.generic.edit import FormView
from django.urls import reverse_lazy


# By default, the homepage is the pad called ‘start’ (props to DokuWiki!)
try:
    HOME_PAD = settings.HOME_PAD
except ImportError:
    HOME_PAD = 'About.md'
try:
    BACKUP_DIR = settings.BACKUP_DIR
except ImportError:
    BACKUP_DIR = None

"""
Set up an HTMLParser for the sole purpose of unescaping
Etherpad’s HTML entities.
cf http://fredericiana.com/2010/10/08/decoding-html-entities-to-text-in-python/
"""

h = HTMLParser()
unescape = h.unescape

"""
Create a regex for our include template tag
"""
include_regex = re.compile("{%\s?include\s?\"([\w._-]+)\"\s?%}")

def makeLeaf ():
    return { 'folders': {}, 'pads': [] }

def insertAt (path=[], tree=[], pad=''):
    if len(path) > 1:
        key = path.pop(0)
        if not key in tree['folders']:
            tree['folders'][key] = makeLeaf()

        tree['folders'][key] = insertAt(path, tree['folders'][key], pad)
    else:
        tree['pads'].append(pad)

    return tree

def insertPad (pad, tree):
    if settings.PAD_NAMESPACE_SEPARATOR in pad.display_slug:
        path = pad.display_slug.split(settings.PAD_NAMESPACE_SEPARATOR)
    else:
        path = []
    
    return insertAt(path, tree, pad)

# Perhaps move to the model?
def makePadPublic (pad, n=0):
    if not pad.is_public:
        epclient = EtherpadLiteClient(pad.server.apikey, settings.API_LOCAL_URL if settings.API_LOCAL_URL else pad.server.apiurl)
        tail = '' if n == 0 else '-{}'.format(n)
        publicid = pad.name+tail

        try:
            res = epclient.sendClientsMessage(pad.padid, "Please continue editing in the publicversion of this pad")
            print(res)
            res = epclient.copyPad(pad.padid, publicid)
            pad.is_public = True
            pad.publicpadid = publicid
            pad.save()

            return pad
        
        except ValueError:
            return makePadPublic(pad, n+1)

def makePadPrivate(pad):
    if pad.is_public:
        epclient = EtherpadLiteClient(pad.server.apikey, settings.API_LOCAL_URL if settings.API_LOCAL_URL else pad.server.apiurl)
        res = epclient.movePad(pad.publicpadid, pad.padid, force=True)

        pad.is_public = False
        pad.publicpadid = ''
        pad.save()
        return pad

# Filter out forbidden
def filterPadSlug(slug):
    # Replace spaces by '_'
    slug = re.sub(r'\s', '_', slug)
    # Replace forbidden characters
    slug = re.sub(r'[/]', '', slug)

    return slug 

def ensurePadExtension(slug):
    name, ext = os.path.splitext(slug)

    if settings.PAD_FORCE_EXTENSION:
        if ext.lower() not in settings.PAD_ALLOWED_EXTENSIONS:
            ext = settings.PAD_DEFAULT_EXTENSION

        return '{}{}'.format(name, ext.lower())

    return '{}{}'.format(name, ext.lower()) 

# FIXME: better name
def numerizePadName (name, n=0):
    name, ext = os.path.splitext(name)

    if n > 0:
        name = '{}-{}'.format(name, n)

    return '{}{}'.format(name, ext)

def treatPadName(slug, n):
    return numerizePadName(ensurePadExtension(filterPadSlug(slug)), n)

def createPad (slug, server, group, n=0):
    if n < 25:
        try:
            safe_slug = treatPadName(slug, n)
            pad = Pad(
                name=slugify(safe_slug)[:42], # This is the slug internally used by etherpad
                display_slug=safe_slug, # This is the slug we get to change afterwards
                server=group.server,
                group=group
            )

            pad.save()
            return pad
        except ValueError:
            # Pad already exists on the server
            return createPad(slug=slug, server=server, group=group, n=n+1)
        except IntegrityError:
            # Pad existed in the database, but not on the server
            # delete the created pad
            pad.Destroy()
            return createPad(slug=slug, server=server, group=group, n=n+1)

    return False

# Move as a property to the model ?
def getFolderName (slug):
    if settings.PAD_NAMESPACE_SEPARATOR in slug:
        return slug.rsplit(settings.PAD_NAMESPACE_SEPARATOR, 1)[0]
    else:
        return None

@login_required(login_url='/accounts/login')
def padCreate(request, prefix=''):
    """
    Create a pad
    """    
    
    # normally the ‘pads’ context processor should have made sure that these objects exist:
    author = PadAuthor.objects.get(user=request.user)
    group = author.group.all()[0]
    
    if request.method == 'POST':  # Process the form
        form = forms.PadCreate(request.POST)
        if form.is_valid():
            slug = re.sub(r'\s+', '_', form.cleaned_data['name'])
            slug = slug.strip(":")  # avoids leading and trailing "::"
            pad = createPad(slug=slug, server=group.server, group=group)

            return HttpResponseRedirect(reverse('pad-write', args=(pad.display_slug,) ))
    else: 
        # No form to process so create a fresh one
        # prefix should contain the name of the folder
        form = forms.PadCreate({'group': group.groupID, 'name': wikifyPath(ensureTrailingSlash(prefix) if prefix else '')})

    con = {
        'form': form,
        'pk': group.pk,
        'title': _('Create pad in %(grp)s') % {'grp': group}
    }
    con.update(csrf(request))
    return render(
        request,
        'pad-create.html',
        con,
    )


@login_required(login_url='/etherpad')
def padDelete(request, pk):
    """Delete a given pad
    """
    pad = get_object_or_404(Pad, pk=pk)

    # Any form submissions will send us back to the profile
    if request.method == 'POST':
        if 'confirm' in request.POST:
            pad.delete()
        return HttpResponseRedirect('/manage/')

    con = {
        'action': reverse('pad-delete', kwargs={'pk': pk}),
        'question': _('Really delete the pad {}?'.format(str(pad))),
        'title': _('Deleting {}'.format(str(pad))),
        'label': _('Delete')
    }
    con.update(csrf(request))
    return render(
        request,
        'pads/confirm.html',
        con
    )


def renamePad(pad, slug, n=0):
    pad.display_slug = treatPadName(slug, n)
    
    while n < settings.MAX_PAD_SAVE_TRIES:
        try:
            return pad.save()
        except IntegrityError:
            return renamePad(pad, slug, n+1)


@login_required(login_url='/etherpad')
def padRename(request, pk):
    pad = get_object_or_404(Pad, pk=pk)

    if request.method == 'POST':
        form = ethertoffForms.PadRename(request.POST)
        if form.is_valid():
            slug = re.sub(r'\s+', '_', form.cleaned_data['name'])
            slug = slug.strip(":")  # avoids leading and trailing "::"
            renamePad(pad, slug)

            path = getFolderName(pad.display_slug)
            if path:
                path.replace(settings.PAD_NAMESPACE_SEPARATOR, '/')
                return redirect('manage', path=path)
            else:
                return redirect('manage')

    else:
        form = ethertoffForms.PadRename({
            'pk': pad.pk,
            'name': pad.display_slug
        })

    context = {
        'form': form,
        'pk': pad.pk,
        'name': pad.display_slug,
        'title': _('Rename pad {}').format(str(pad))
    }

    context.update(csrf(request))

    return render(
        request,
        'pad-rename.html',
        context
    )

class RenameFolderView(FormView):
    template_name = 'folder-rename.html'
    form_class = RenameFolderForm
    success_url = reverse_lazy('manage')

    def get_initial(self):
        """Return the initial data to use for forms on this view."""
        old_name = self.kwargs.get("prefix", "") 
        old_name = old_name.replace('/', settings.PAD_NAMESPACE_SEPARATOR)
        old_name = old_name.strip(":")  # avoids leading and trailing "::"
        self.initial.update({"old_name": old_name})
        self.initial.update({"new_name": old_name})
        return super().get_initial()


    def form_valid(self, form):
        old_name = form.cleaned_data.get('old_name')
        new_name = form.cleaned_data.get('new_name')
        for pad in Pad.objects.filter(display_slug__startswith=old_name):
            current_display_slug = pad.display_slug
            new_display_slug = new_name + current_display_slug[len(old_name):]
            pad.display_slug = new_display_slug
            pad.save()
        return super().form_valid(form)

@login_required(login_url='/etherpad')
def padPublic(request, pk):
    """Delete a given pad
    """
    pad = get_object_or_404(Pad, pk=pk)

    # Any form submissions will send us back to the profile

ethertoff/templates/all.html
{% extends "base.html" %}
{% load wikify %}

{% block content %}
    <ul id="pads_list">
        {% for pad in pads %}
            <li><a data-uid="{{ pad.display_slug }}" href="{% if mode == 'write' %}{% url 'pad-write' slug=pad.display_slug %}{% else %}{% url 'pad-read' 'r' pad.display_slug %}{% endif %}" class="pad-link">{{ pad.display_slug|dewikify }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

ethertoff/templates/base.html
{% load wikify ethertoff_tags static %}<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" {% if meta.language %} lang="{{ meta.language.0 }}" {% endif %} moznomarginboxes mozdisallowselectionprint>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}" type="text/css" media="all">
    
    {% block extra_styles %}
        <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
        <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
    {% endblock %}


    <script src="{% static 'js/less-1.4.1.min.js' %}" type="text/javascript"> </script>
    <script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"> </script>
    <script src="{% static 'js/underscore.js' %}" type="text/javascript"> </script>

    {% block head_meta %}{% endblock %}

    <title>{{ site_name }}{% if pad %} → {{ pad.display_slug|dewikify }}{% endif %}</title>
    
</head>
<body class="pad-{{ pad.display_name|slugify }} {{ mode }}-mode {% if user.is_authenticated and author %}logged-in{% else %}logged-out{% endif %} {% block bodyclasses %}{% endblock %}">
    <nav id="nav-left">
        <h1><a id="logo" data-article="{% block data_article %}{% endblock%}" href="/">{{ site_name }}</a></h1>
        <a class="button screen-only" href="/r/About.md">About</a>
        
        <!-- 
        <div id="sort-by">Sort by:
            <a class="{% if sort == 'date' %}active{% endif %} button screen-only" href="/?sort=date">Date</a>
            <a class="{% if sort == 'tags' %}active{% endif %} button screen-only" href="/?sort=tags">Tag</a>
            <a class="{% if sort == 'authors' %}active{% endif %} button screen-only" href="/?sort=authors">Author</a>
        </div>-->
        {% block extra_nav %}{% endblock %}
        
        <a class="button screen-only" href="{% url 'all' %}">List</a>

        {% if user.is_authenticated and author %}
        <div id="staff-menu" class="private">
            <span class="screen-only">{{ author.full_name_with_prefix }}</span>
            <a class="button screen-only" href="{% url 'logout' %}{% if pad %}?next={% url 'pad-read' 'r' pad.display_slug %}{% endif %}">Log out</a>
            <a class="button screen" href="{% url 'password_change' %}">Change password</a>
            <a class="button screen-only" href="{% url 'pad-create' %}">Create</a>
            <a class="button screen-only" href="{% url 'generate' %}">Generate static version</a>
            <a class="button screen-only" href="/static/generated/">View static version</a>
            <a class="button screen-only" href="/w/screen.css">screen.css</a>
            <a class="button screen-only" href="/w/laser.css">laser.css</a>
            <a class="button screen-only" href="/w/offset.css">offset.css</a>
            <a class="button screen-only" href="/w/documentation.md">documentation</a>
            {% else %}
            <a class="button" href="{% url 'login' %}">Log in</a>
            {% endif %}
        </div>
    </nav>
    <nav id="nav-right">
        {% if pad %}
            <a class="button screen-only read-button" href="{% url 'pad-read' 'r' pad.display_slug %}">Read</a>
            <a class="button screen-only slide-button" href="{% url 'pad-read' 's' pad.display_slug %}">Slide</a>
            <a class="button screen-only" href="{% url 'pad-read' 'p' pad.display_slug %}">Print</a>
            {% if pad.is_public or user.is_authenticated %}
                <a class="button screen-only write-button" href="{% url 'pad-write' pad.display_slug %}">Write</a>
            {% else %}
                <a class="button screen-only write-button login-required" href="{% url 'login' %}">Write</a>
            {% endif %}
        {% endif %}
    </nav>
    <div class="wrap">
        <div class="left-side screen-only">
            {% block title_left %}{% endblock %}
        </div>

        <div class="middle">
            {% block title %}{% endblock %}
        </div>

        <div class="right-side screen-only">
            {% block title_right %}{% endblock %}
        </div>
    </div>

    <div class="wrap">
        <div class="left-side screen-only">
        </div>
        <div class="middle">
            <div id="content" class="{% block contentclasses %}{% endblock %}">
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="right-side screen-only">
            {% block rightside %}{% endblock %}
        </div>
    </div>
    {% block extraui %}{% endblock %}


    

    <script src="{% static 'js/ethertoff.js' %}" type="text/javascript" charset="utf-8"> </script>
    <script src="{% static 'js/comments/comments.js' %}" type="text/javascript" charset="utf-8"> </script>

    {% if user.is_authenticated and author %}
        <script>
            $(function() {
                $("#content").revealComments();
            });
        </script>
    {% endif %}


{% block scripts %}{% endblock %}
</body>
</html>

ethertoff/templates/folder-rename.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_styles %}
      <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
      <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
{% endblock %}
  
{% block title %}
      <h1>{{ title }}</h1>
{% endblock %}

{% block content %}
  <form action="{% url 'folder-rename' %}" method="post">
        {% csrf_token %}
        Old folder name: "{{ form.old_name.value }}"<br />  
        {{ form.old_name.as_hidden }}
        {{ form.new_name }}
        <input class="submit" type="submit" value="{% trans "Rename" %}" />
  </form>
  <legend></legend>
{% endblock %}

ethertoff/templates/form.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>ethertoff</title>
    <link rel="stylesheet/less" href="{% static 'less/ethertoff.less' %}" type="text/css" media="screen" charset="utf-8">
    <script src="{% static 'js/less-1.4.1.min.js' %}" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
        body {
            background: none;
        }
        
    </style>
</head>
<body>
<form id="email-form" action="{% url 'ethertoff-issue-send' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div>
        <input style="width: 45%; display: inline; margin-right: 10px;" id="id_name" maxlength="50" name="name" type="text" value="{{ user.get_full_name }}"/>
        <!--<input style="width: 45%; display: inline;" id="id_email" name="email" type="text" value="{{ user.email }}" />-->
    </div>
    <div style="margin-top: 3px;">
        <label style="width: 25%; display: inline;" for="id_subject">Subject</label> 
        <input style="width: 73%; display: inline;" id="id_subject" maxlength="100" name="subject" type="text" />
    </div>
    <div style="margin-top: 3px;">
        <textarea style="width: 96%; height: 6em;" id="id_message" name="message"></textarea>
    </div>
    <p><input type="submit" value="Send"></p>
</form>
</body>
</html>

ethertoff/templates/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
<h1>{% trans "Logout" %}</h1>
{% endblock %}

{% block content %}
<h2>{% trans "You have been logged out." %} <a href="{% url 'login' %}">{% trans "Log back in." %}</a></h2>

{% endblock %}

ethertoff/templates/manage-tree.html
{% extends "base.html" %}
{% load wikify %}

{% block content %}
    <section class="pad-list--path">
        <a href="{% url 'manage' %}">root</a>
        {% for name, path in crumbs %}
            {% if path %}
                > <a href="{% url 'manage' path|pathString  %}">{{ name }}</a>
            {% endif %}
        {% endfor %}
    </section>
    <ul id="pads_list" class="manage_list">
        {% for folder in folders %}
            <li><a href="{% url 'manage' folder|addPath:folderPath %}">&#128448; {{ folder }}</a>
              <section class="actions">
                <a href="{% url 'folder-rename' folder|addPath:folderPath %}" class="button button--rename">rename</a>
              </section>
            </li>
        {% endfor %}
        {% for pad in tree.pads %}
            <li>
              <a data-uid="{{ pad.display_slug }}" href="{% url 'pad' mode=PAD_OPEN_MODE slug=pad.display_slug %}" class="pad-link">
                {{ pad.display_slug|stripPath:folderPath|dewikify }}
                {% if pad.is_public %}(public){% endif %}
              </a>
              <section class="actions">
                {% if pad.is_public %}
                    <a href="{% url 'pad-private' pad.pk %}" class="button button--private">make private</a>
                {% else %}
                    <a href="{% url 'pad-public' pad.pk %}" class="button button--public">make public</a>
                {% endif %}
                <a href="{% url 'pad-rename' pad.pk %}" class="button button--rename">rename</a>
                <a href="{% url 'pad-delete' pad.pk %}" class="button button--delete">delete</a>
              </section>
            </li>
        {% endfor %}
    </ul>
    <section class="pad-list--actions">
        <a href="{% url 'pad-create' folderPathString %}">+ create pad</a>
    </section>
{% endblock %}

ethertoff/templates/manage.html
{% extends "base.html" %}
{% load wikify %}

{% block content %}
    <ul id="pads_list" class="manage_list">
        {% for pad in pads %}
            <li>
              <a data-uid="{{ pad.display_slug }}" href="{% if mode == 'write' %}{% url 'pad-write' slug=pad.display_slug %}{% else %}{% url 'pad-read' 'r' pad.display_slug %}{% endif %}" class="pad-link">{{ pad.display_slug|dewikify }}</a>
              <section class="actions">
                <a href="{% url 'pad-delete' pad.pk %}" class="button button--delete">delete</a>
              </section>
            </li>
        {% endfor %}
    </ul>

    <section class="pagination">
      <section class="step-links previous">
        {% if pads.has_previous %}
            <a href="{% url 'manage' 1 %}">&laquo; first</a>
            <a href="{% url 'manage' pads.previous_page_number %}">previous</a>
        {% endif %}
      </section>
    
      Page {{ pads.number }} of {{ pads.paginator.num_pages }}
    
      <section class="step-links next">
          {% if pads.has_next %}
              <a href="{% url 'manage' pads.next_page_number %}">next</a>
              <a href="{% url 'manage' pads.paginator.num_pages %}">last &raquo;</a>
          {% endif %}
      </section>
    </section>
{% endblock %}

ethertoff/templates/pad-public.html
{% extends "base.html" %}
{% load ethertoff_tags %}

{% block extra_styles %}
  <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
  <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
{% endblock %}

{% block title %}
    <header>
    {% if meta.authors %}
        <p class="authors">{{ meta.authors|natural_join:'et' }}</p>
    {% endif %}
    <h1>
        {{ meta.title.0|default:pad.display_slug }}
    </h1>
    </header>
{% endblock %}

{% block content %}
  {% if error %}
  <div id="main">
    <div id="errors">
      <h2>Errors:</h2>
      <p>{{error}}</p>
    </div>
  </div>
  {% else %}
  <iframe id="ether" src="{{link}}{% if uname %}?userName={{uname}}{% endif %}"> </iframe>

  <script type="text/javascript">
      /**
       * This little script is necessary for some browsers that don't respect the
       * height css attribute on iframes.
       */
      function resizeEtherpad() {
        height = jQuery(window).height()*94/100;
        jQuery('#wrapper iframe').height(height);
      }

      jQuery(document).ready( function() {
        resizeEtherpad()
        jQuery(window).resize(resizeEtherpad);
      });
  </script>
  {% endif %}

{% endblock %}

ethertoff/templates/pad-rename.html
{% extends "base.html" %}
{% load i18n %}

{% block extra_styles %}
      <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
      <link rel="stylesheet" href="{% url 'css-print' %}" type="text/css" media="print">
{% endblock %}
  
{% block title %}
      <h1>{{ title }}</h1>
{% endblock %}

{% block content %}
  <form action="{% url 'pad-rename' pk=pk %}" method="post">
        {% csrf_token %}
        {% trans "Old pad name" %}: {{ name }}<br />  
        {% trans "New pad name" %}: {{ form.name }}
        <input class="submit" type="submit" value="{% trans "Rename" %}" />
  </form>
  <legend></legend>
{% endblock %}

ethertoff/templates/pad-slide.html
{% extends "base.html" %}
{% load wikify ethertoff_tags static %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% url 'css-screen' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'js/slidy.css' %}" type='text/css' media="all" />
    <link rel="stylesheet" href="{% url 'css-slide' %}" type='text/css' media="all" />
{% endblock %}


{% block head_meta %}
    <meta property="og:type" content="article"/>
{% if meta %}

    {% if meta.authors %}
        {% for author in meta.authors %}
            <meta property="dc:creator" content="{{ author }}" />
        {% endfor %}
    {% endif %}
    {% if meta.language %}{% for language in meta.language %}<meta property="dc:language" content="{{ language|lower }}" />{% endfor %}{% endif %}

    <meta property="dc:identifier" content="{{ meta.id.0 }}" />
    {% if meta.type %}<meta property="dc:type" content="{{ meta.type.0 }}" />{% endif %}
{% endif %}
{% endblock %}


{% block data_article %}{{ meta.authors|natural_join:'&'|markdown_filter|no_p }}, {{ meta.title.0 }}{% endblock %}

{% block bodyclasses%}{% if meta.host %}{{ meta.host.0|lower }}{% endif %} {% if meta.type %}{{ meta.type.0|lower }}{% endif %}{% endblock %}
{% block contentclasses%}{% if meta.host %}{{ meta.host.0|lower }}{% endif %} {% if meta.type %}{{ meta.type.0|lower }}{% endif %}{% endblock %}


{% block content %}
    {{ text|safe }}
{% endblock %}

{% block scripts %}
    <script src="/static/js/slidy.js"> </script>

    <script>
    // REMOVE THIS WHOLE SCRIPT TAG FOR LOCAL VERSION //
    $(document).ready(function(){
        // DIV WRAPPER AROUND EACH H2
        $("#content h2").each(function(){
            h2 = $(this).attr('id');
            $(this).nextUntil('h2').andSelf().wrapAll('<div class="slide ' + h2 + '"></div>');
        });
    });
    </script>
{% endblock %}